### ISSUE TITLE
Exception on player hurt

### ISSUE THREAD

**Issue by TsunaDev** [audiomaster99/CS2-SpawnProt#1]
Whenever a player is hurt, an exception related to `get_ArmorValue()` is thrown:

```
[EROR] (cssharp:Core) Error invoking callback System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.MissingMethodException: Method not found: 'Int32 ByRef CounterStrikeSharp.API.Core.CCSPlayerPawnBase.get_ArmorValue()'.
at CS2_SimpleAdmin.CS2_SimpleAdmin.OnPlayerHurt(EventPlayerHurt event, GameEventInfo info)
at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of inner exception stack trace ---
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by itsAudioo** [comment]
> Whenever a player is hurt, an exception related to `get_ArmorValue()` is thrown:
> 
> ```
> [EROR] (cssharp:Core) Error invoking callback System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> ---> System.MissingMethodException: Method not found: 'Int32 ByRef CounterStrikeSharp.API.Core.CCSPlayerPawnBase.get_ArmorValue()'.
> at CS2_SimpleAdmin.CS2_SimpleAdmin.OnPlayerHurt(EventPlayerHurt event, GameEventInfo info)
> at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
> at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> --- End of inner exception stack trace ---
> at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> at System.Delegate.DynamicInvokeImpl(Object[] args)
> at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
> ```

Use latest build
Btw error you sent is from simple admin

**Comment by TsunaDev** [comment]
😮 Oops sorry, I was testing your plugin when it came up so I jumped to conclusions... :/

**Comment by itsAudioo** [comment]
> 😮 Oops sorry, I was testing your plugin when it came up so I jumped to conclusions... :/

it happens :D
