### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Armageddon87270** [audiomaster99/CS2-SpawnProt#2]
Hi,

Error 

2024-10-19 20:25:59.140 +02:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetDeclaredClass[T](IntPtr pointer, String className, String memberName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 101
   at SpawnProt.SpawnProt.HandlePlayerModel(CCSPlayerController player)
   at SpawnProt.SpawnProt.<>c__DisplayClass10_0.<OnPlayerSpawn>b__0()
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by itsAudioo** [comment]
this issue should be fixed with latest release https://github.com/audiomaster99/SpawnProtection/releases/tag/v1.0.0
sorry for late update and response
